
#
#  Makefile
#  Copyright (c) 2001-2003 Brad Proctor
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

#
# $Id: Makefile,v 1.4 2003/01/20 04:23:26 fredlie Exp $
#

TOP = ../..
TARGET = ctype.o

SRC += __ctype.c
SRC += __tolower.c
SRC += __toupper.c
SRC += isalnum.c
SRC += isalpha.c
SRC += isascii.c
SRC += iscntrl.c
SRC += isdigit.c
SRC += isgraph.c
SRC += islower.c
SRC += isprint.c
SRC += ispunct.c
SRC += isspace.c
SRC += isupper.c
SRC += isxdigit.c
SRC += toascii.c
SRC += tolower.c
SRC += toupper.c

include $(TOP)/Makefile.def
