
TOP = ../..

TARGET = strings.o

SRC += bcmp.c
SRC += bcopy.S
SRC += bzero.S
SRC += ffs.S
SRC += index.S
SRC += rindex.S
SRC += strdup.c
SRC += strcasecmp.c
SRC += strncasecmp.c

include $(TOP)/Makefile.def
