
/*
 *  tokens.c
 *  Copyright (c) 2001-2003 Brad Proctor
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * $Id: tokens.c,v 1.2 2003/01/02 23:31:21 fredlie Exp $
 */


#include "as.h"
#include "parse.h"

static token_type a_tokens[] =
{
   {"aaa",        tONEBYTE,         0x37},
   {"aad",        tAAD,             0},
   {"aam",        tAAM,             0},
   {"aas",        tONEBYTE,         0x3F},
   {"adc",        tARITH,           0x10},
   {"add",        tARITH,           0x00},
   {"addpd"},
   {"addps"},
   {"addsd"},
   {"addss"},
   {"ah",         tREG8,            4},
   {"al",         tREG8,            0},
   {"and",        tARITH,           0x20},
   {"andnpd"},
   {"andnps"},
   {"andpd"},
   {"andps"},
   {"arpl",       tARPL,            0},
   {"ax",         tREG16,           0},
   {0},
};

static token_type b_tokens[] =
{
   {"bh",         tREG8,            7},
   {"bl",         tREG8,            3},
   {"bound",      tBOUND,           0},
   {"bp",         tREG16,           5},
   {"bsf",        tBSx,             0x0FBC},
   {"bsr",        tBSx,             0x0FBD},
   {"bswap",      tBSWAP,           0},
   {"bt",         tBTx,             4},
   {"btc",        tBTx,             7},
   {"btr",        tBTx,             6},
   {"bts",        tBTx,             5},
   {"bx",         tREG16,           3},
   {0},
};

static token_type c_tokens[] =
{
   {"call",          tCALL,         0},
   {"cbw",           tONEBYTE16,    0x98},
   {"cdq",           tONEBYTE32,    0x99},
   {"ch",            tREG8,         5},
   {"cl",            tREG8,         1},
   {"clc",           tONEBYTE,      0xF8},
   {"cld",           tONEBYTE,      0xFC},
   {"clflush"},
   {"cli",           tONEBYTE,      0xFA},
   {"clts",          tTWOBYTE,      0x0F06},
   {"cmc",           tONEBYTE,      0xF5},
   {"cmova",         tCMOVcc,       7},
   {"cmovae",        tCMOVcc,       3},
   {"cmovb",         tCMOVcc,       2},
   {"cmovbe",        tCMOVcc,       6},
   {"cmovc",         tCMOVcc,       2},
   {"cmove",         tCMOVcc,       4},
   {"cmovg",         tCMOVcc,       15},
   {"cmovge",        tCMOVcc,       13},
   {"cmovl",         tCMOVcc,       12},
   {"cmovle",        tCMOVcc,       14},
   {"cmovna",        tCMOVcc,       6},
   {"cmovnae",       tCMOVcc,       2},
   {"cmovnb",        tCMOVcc,       3},
   {"cmovnbe",       tCMOVcc,       7},
   {"cmovnc",        tCMOVcc,       3},
   {"cmovne",        tCMOVcc,       5},
   {"cmovng",        tCMOVcc,       14},
   {"cmovnge",       tCMOVcc,       12},
   {"cmovnl",        tCMOVcc,       13},
   {"cmovnle",       tCMOVcc,       15},
   {"cmovno",        tCMOVcc,       1},
   {"cmovnp",        tCMOVcc,       11},
   {"cmovns",        tCMOVcc,       9},
   {"cmovnz",        tCMOVcc,       5},
   {"cmovo",         tCMOVcc,       0},
   {"cmovp",         tCMOVcc,       10},
   {"cmovpe",        tCMOVcc,       10},
   {"cmovpo",        tCMOVcc,       11},
   {"cmovs",         tCMOVcc,       8},
   {"cmovz",         tCMOVcc,       4},
   {"cmp",           tARITH,        0x38},
   {"cmpeqps"},
   {"cmpeqss"},
   {"cmpleps"},
   {"cmpless"},
   {"cmpltps"},
   {"cmpltss"},
   {"cmpneqps"},
   {"cmpneqss"},
   {"cmpnleps"},
   {"cmpnless"},
   {"cmpnltps"},
   {"cmpnltss"},
   {"cmpordps"},
   {"cmpordss"},
   {"cmppd"},
   {"cmpps"},
   {"cmpsb",         tONEBYTE,      0xA6},
   {"cmpsd",         tONEBYTE32S,   0xA7},
   {"cmpss"},
   {"cmpsw",         tONEBYTE16S,    0xA7},
   {"cmpunordps"},
   {"cmpunordss"},
   {"cmpxchg"},
   {"cmpxchg486"},
   {"cmpxchg8b"},
   {"comisd"},
   {"comiss"},
   {"cpuid",         tTWOBYTE,      0x0FA2},
   {"cr0",           tCREG,         0},
   {"cr1",           tCREG,         1},
   {"cr2",           tCREG,         2},
   {"cr3",           tCREG,         3},
   {"cr4",           tCREG,         4},
   {"cr5",           tCREG,         5},
   {"cr6",           tCREG,         6},
   {"cr7",           tCREG,         7},
   {"cs",            tSREG},
   {"cvtdq2pd"},
   {"cvtdq2ps"},
   {"cvtpi2ps"},
   {"cvtpd2dq"},
   {"cvtpd2pi"},
   {"cvtpd2ps"},
   {"cvtpi2pd"},
   {"cvtpi2ps"},
   {"cvtps2dq"},
   {"cvtps2pd"},
   {"cvtps2pi"},
   {"cvtsd2si"},
   {"cvtsd2ss"},
   {"cvtsi2sd"},
   {"cvtsi2ss"},
   {"cvtss2sd"},
   {"cvtss2si"},
   {"cvttpd2pi"},
   {"cvttpd2dq"},
   {"cvttps2dq"},
   {"cvttps2pi"},
   {"cvttsd2si"},
   {"cvttss2si"},
   {"cwd",           tONEBYTE16,    0x99},
   {"cwde",          tONEBYTE32,    0x98},
   {"cx",            tREG16,        1},
   {0},
};

static token_type d_tokens[] =
{
   {"daa",           tONEBYTE,      0x27},
   {"das",           tONEBYTE,      0x2F},
   {"db",            tDB,           0},
   {"dd",            tDD,           0},
   {"dec",           tDEC,          0},
   {"dh",            tREG8,         6},
   {"di",            tREG16,        7},
   {"div"},
   {"divpd"},
   {"divps"},
   {"divsd"},
   {"divss"},
   {"dl",            tREG8,         2},
   {"dq",            tDQ,           0},
   {"dr0",           tDREG,         0},
   {"dr1",           tDREG,         1},
   {"dr2",           tDREG,         2},
   {"dr3",           tDREG,         3},
   {"dr4",           tDREG,         4},
   {"dr5",           tDREG,         5},
   {"dr6",           tDREG,         6},
   {"dr7",           tDREG,         7},
   {"ds",            tSREG},
   {"dt",            tDT,           0},
   {"dup",           tDUP,          0},
   {"dw",            tDW,           0},
   {"dx",            tREG16,        2},
   {0},
};

static token_type e_tokens[] =
{
   {"eax",           tREG32,        0},
   {"ebp",           tREG32,        5},
   {"ebx",           tREG32,        3},
   {"ecx",           tREG32,        1},
   {"edi",           tREG32,        7},
   {"edx",           tREG32,        2},
   {"emms",          tTWOBYTE,      0x0F77},
   {"enter",         tENTER,        0},
   {"equ",           tEQU,          0},
   {"es",            tSREG},
   {"esi",           tREG32,        6},
   {"esp",           tREG32,        4},
   {0},
};

static token_type f_tokens[] =
{
   {"f2xm1",         tTWOBYTE,      0xD9F0},
   {"fabs",          tTWOBYTE,      0xD9E1},
   {"fadd"},
   {"faddp"},
   {"fbld"},
   {"fbstp"},
   {"fchs",          tTWOBYTE,      0xD9E0},
   {"fclex",         tTHREEBYTE,    0x9BDBE2},
   {"fcmovb"},
   {"fcmovbe"},
   {"fcmove"},
   {"fcmovnb"},
   {"fcmovnbe"},
   {"fcmovne"},
   {"fcmovnu"},
   {"fcmovu"},
   {"fcom"},
   {"fcomi"},
   {"fcomip"},
   {"fcomp"},
   {"fcompp",        tTWOBYTE,      0xDED9},
   {"fcos",          tTWOBYTE,      0xD9FF},
   {"fdecstp",       tTWOBYTE,      0xD9F6},
   {"fdisi",         tTHREEBYTE,    0x9BDBE1},
   {"fdiv"},
   {"fdivp"},
   {"fdivr"},
   {"fdivrp"},
   {"femms",         tTWOBYTE,      0x0F0E},
   {"feni",          tTHREEBYTE,    0x9BDBE0},
   {"ffree"},
   {"fiadd"},
   {"ficom"},
   {"ficomp"},
   {"fidiv"},
   {"fidivr"},
   {"fild"},
   {"fimul"},
   {"fincstp",       tTWOBYTE,      0xD9F7},
   {"finit",         tTHREEBYTE,    0x9BDBE3},
   {"fist"},
   {"fistp"},
   {"fisub"},
   {"fisubr"},
   {"fld"},
   {"fld1",          tTWOBYTE,      0xD9E8},
   {"fldcw"},
   {"fldenv"},
   {"fldl2e",        tTWOBYTE,      0xD9EA},
   {"fldl2t",        tTWOBYTE,      0xD9E9},
   {"fldlg2",        tTWOBYTE,      0xD9EC},
   {"fldln2",        tTWOBYTE,      0xD9ED},
   {"fldpi",         tTWOBYTE,      0xD9EB},
   {"fldz",          tTWOBYTE,      0xD9EE},
   {"fmul"},
   {"fmulp"},
   {"fnclex",        tTWOBYTE,      0xDBE2},
   {"fndisi",        tTWOBYTE,      0xDBE1},
   {"fneni",         tTWOBYTE,      0xDBE0},
   {"fninit",        tTWOBYTE,      0xDBE3},
   {"fnop",          tTWOBYTE,      0xD9D0},
   {"fnsave"},
   {"fnstcw"},
   {"fnstenv"},
   {"fnstsw"},
   {"fpatan",        tTWOBYTE,      0xD9F3},
   {"fprem",         tTWOBYTE,      0xD9F8},
   {"fprem1",        tTWOBYTE,      0xD9F5},
   {"fptan",         tTWOBYTE,      0xD9F2},
   {"frndint",       tTWOBYTE,      0xD9FC},
   {"frstor"},
   {"fs",            tSREG},
   {"fsave"},
   {"fscale",        tTWOBYTE,      0xD9FD},
   {"fsetpm",        tTWOBYTE,      0xDBE4},
   {"fsin",          tTWOBYTE,      0xD9FE},
   {"fsincos",       tTWOBYTE,      0xD9FB},
   {"fsqrt",         tTWOBYTE,      0xD9FA},
   {"fst"},
   {"fstcw"},
   {"fstenv"},
   {"fstp"},
   {"fstsw"},
   {"fsub"},
   {"fsubp"},
   {"fsubr"},
   {"fsubrp"},
   {"ftst",          tTWOBYTE,      0xD9E4},
   {"fucom"},
   {"fucomi"},
   {"fucomip"},
   {"fucomp"},
   {"fucompp",       tTWOBYTE,      0xDAE9},
   {"fxam",          tTWOBYTE,      0xD9E5},
   {"fxch",          tTWOBYTE,      0xD9C9},
   {"fxrstor"},
   {"fxsave"},
   {"fxtract",       tTWOBYTE,      0xD9F4},
   {"fyl2x",         tTWOBYTE,      0xD9F1},
   {"fyl2xp1",       tTWOBYTE,      0xD9F9},
   {0},
};

static token_type g_tokens[] =
{
   {"gs",            tSREG},
   {0},
};

static token_type h_tokens[] =
{
   {"hlt",           tONEBYTE,      0xF4},
   {0},
};

static token_type i_tokens[] =
{
   {"ibts"},
   {"icebp",         tONEBYTE,      0xF1},
   {"idiv",          tIDIV,         0},
   {"imul",          tIMUL,         0},
   {"in",            tIN,           0},
   {"inc",           tINC,          0},
   {"incbin"},
   {"ins"},
   {"insb",          tONEBYTE,      0x6C},
   {"insd",          tONEBYTE32,    0x6D},
   {"insw",          tONEBYTE16,    0x6D},
   {"int",           tINT,          0},
   {"int01",         tONEBYTE,      0xF1},
   {"int03",         tONEBYTE,      0xCC},
   {"int1",          tONEBYTE,      0xF1},
   {"int3",          tONEBYTE,      0xCC},
   {"into",          tONEBYTE,      0xCE},
   {"invd",          tTWOBYTE,      0x0F08},
   {"invlpg",        tINVLPG,       0},
   {"iret",          tONEBYTE,      0xCF},
   {"iretd",         tONEBYTE32,    0xCF},
   {"iretw",         tONEBYTE16,    0xCF},
   {0},
};

static token_type j_tokens[] =
{
   {"ja",            tJcc,          7},
   {"jae",           tJcc,          3},
   {"jb",            tJcc,          2},
   {"jbe",           tJcc,          6},
   {"jc",            tJcc,          2},
   {"jcxz"},
   {"je",            tJcc,          4},
   {"jecxz"},
   {"jg",            tJcc,          15},
   {"jge",           tJcc,          13},
   {"jl",            tJcc,          12},
   {"jle",           tJcc,          14},
   {"jmp",           tJMP,          0},
   {"jna",           tJcc,          6},
   {"jnae",          tJcc,          2},
   {"jnb",           tJcc,          3},
   {"jnbe",          tJcc,          7},
   {"jnc",           tJcc,          3},
   {"jne",           tJcc,          5},
   {"jng",           tJcc,          14},
   {"jnge",          tJcc,          12},
   {"jnl",           tJcc,          13},
   {"jnle",          tJcc,          15},
   {"jno",           tJcc,          1},
   {"jnp",           tJcc,          11},
   {"jns",           tJcc,          9},
   {"jnz",           tJcc,          5},
   {"jo",            tJcc,          0},
   {"jp",            tJcc,          10},
   {"jpe",           tJcc,          10},
   {"jpo",           tJcc,          11},
   {"js",            tJcc,          8},
   {"jz",            tJcc,          4},
   {0},
};

static token_type k_tokens[] =
{
   {0},
};

static token_type l_tokens[] =
{
   {"lahf",          tONEBYTE,      0x9F},
   {"lar"},
   {"ldmxcsr"},
   {"lds"},
   {"lea",           tLEA,          0},
   {"leave",         tONEBYTE,      0xC9},
   {"les"},
   {"lfs"},
   {"lfence"},
   {"lgdt"},
   {"lgs"},
   {"lidt"},
   {"lldt"},
   {"lmsw"},
   {"loadall",       tTWOBYTE,      0x0F07},
   {"loadall286",    tTWOBYTE,      0x0F05},
   {"lock"},
   {"lods"},
   {"lodsb",         tONEBYTE,      0xAC},
   {"lodsd",         tONEBYTE32,    0xAD},
   {"lodsw",         tONEBYTE16,    0xAD},
   {"loop",          tLOOP},
   {"loope",         tLOOP},
   {"loopne",        tLOOP},
   {"loopnz",        tLOOP},
   {"loopz",         tLOOP},
   {"lsl"},
   {"lss"},
   {"ltr"},
   {0},
};

static token_type m_tokens[] =
{
   {"maskmovdqu"},
   {"maskmovq"},
   {"maxpd"},
   {"maxps"},
   {"maxsd"},
   {"maxss"},
   {"mfence"},
   {"minpd"},
   {"minps"},
   {"minsd"},
   {"minss"},
   {"mm0",           tMREG,         0},
   {"mm1",           tMREG,         1},
   {"mm2",           tMREG,         2},
   {"mm3",           tMREG,         3},
   {"mm4",           tMREG,         4},
   {"mm5",           tMREG,         5},
   {"mm6",           tMREG,         6},
   {"mm7",           tMREG,         7},
   {"mov",           tMOV},
   {"movapd"},
   {"movaps"},
   {"movd"},
   {"movdqa"},
   {"movdqu"},
   {"movdq2q"},
   {"movhlps"},
   {"movhpd"},
   {"movhps"},
   {"movlhps"},
   {"movlpd"},
   {"movlps"},
   {"movmskpd"},
   {"movmskps"},
   {"movntdq"},
   {"movnti"},
   {"movntpd"},
   {"movntps"},
   {"movntq"},
   {"movq"},
   {"movq2dq"},
   {"movs"},
   {"movsb",         tONEBYTE,      0xA4},
   {"movsd",         tONEBYTE32,    0xA5},
   {"movss"},
   {"movsw",         tONEBYTE16,    0xA5},
   {"movsx"},
   {"movups"},
   {"movzx"},
   {"mul"},
   {"mulpd"},
   {"mulps"},
   {"mulsd"},
   {"mulss"},
   {0},
};

static token_type n_tokens[] =
{
   {"neg"},
   {"nop",           tONEBYTE,      0x90},
   {"not"},
   {0},
};

static token_type o_tokens[] =
{
   {"or",            tARITH,        0x08},
   {"orpd"},
   {"orps"},
   {"out",           tOUT,          0},
   {"outs"},
   {"outsb",         tONEBYTE,      0x6E},
   {"outsd",         tONEBYTE32,    0x6F},
   {"outsw",         tONEBYTE16,    0x6F},
   {0},
};

static token_type p_tokens[] =
{
   {"packssdw"},
   {"packsswb"},
   {"packuswb"},
   {"paddb"},
   {"paddd"},
   {"paddq"},
   {"paddsb"},
   {"paddsiw"},
   {"paddsw"},
   {"paddusb"},
   {"paddusw"},
   {"paddw"},
   {"pand"},
   {"pandn"},
   {"pause"},
   {"paveb"},
   {"pavgb"},
   {"pavgusb"},
   {"pavgw"},
   {"pcmpeqb"},
   {"pcmpeqd"},
   {"pcmpeqw"},
   {"pcmpgtb"},
   {"pcmpgtd"},
   {"pcmpgtw"},
   {"pdistib"},
   {"pextrw"},
   {"pf2id"},
   {"pfacc"},
   {"pfadd"},
   {"pfcmpeq"},
   {"pfcmpge"},
   {"pfcmpgt"},
   {"pfmax"},
   {"pfmin"},
   {"pfmul"},
   {"pfrcp"},
   {"pfrcpit1"},
   {"pfrcpit2"},
   {"pfrsqit1"},
   {"pfrsqrt"},
   {"pfsub"},
   {"pfsubr"},
   {"pi2fd"},
   {"pinsrw"},
   {"pmachriw"},
   {"pmaddwd"},
   {"pmagw"},
   {"pmaxsw"},
   {"pmaxub"},
   {"pminsw"},
   {"pminub"},
   {"pmovmskb"},
   {"pmulhriw"},
   {"pmulhrwc"},
   {"pmulhuw"},
   {"pmulhw"},
   {"pmullw"},
   {"pmvgezb"},
   {"pmvlzb"},
   {"pmvnzb"},
   {"pmvzb"},
   {"pop"},
   {"popa",          tONEBYTE,      0x61},
   {"popad",         tONEBYTE32,    0x61},
   {"popaw",         tONEBYTE16,    0x61},
   {"popf",          tONEBYTE,      0x9D},
   {"popfd",         tONEBYTE32,    0x9D},
   {"popfw",         tONEBYTE16,    0x9D},
   {"por"},
   {"prefetch"},
   {"prefetchnta"},
   {"prefetcht0"},
   {"prefetcht1"},
   {"prefetcht2"},
   {"prefetchw"},
   {"psadbw"},
   {"pshufw"},
   {"pslld"},
   {"psllq"},
   {"psllw"},
   {"psrad"},
   {"psraw"},
   {"psrld"},
   {"psrlq"},
   {"psrlw"},
   {"psubb"},
   {"psubd"},
   {"psubsb"},
   {"psubsiw"},
   {"psubsw"},
   {"psubusb"},
   {"psubusw"},
   {"psubw"},
   {"psubw"},
   {"punpckhbw"},
   {"punpckhdq"},
   {"punpckhwd"},
   {"punpcklbw"},
   {"punpckldq"},
   {"punpcklwd"},
   {"push"},
   {"pusha",         tONEBYTE,      0x60},
   {"pushad",        tONEBYTE32,    0x60},
   {"pushaw",        tONEBYTE16,    0x60},
   {"pushf",         tONEBYTE,      0x9C},
   {"pushfd",        tONEBYTE32,    0x9C},
   {"pushfw",        tONEBYTE16,    0x9C},
   {"pxor"},
   {0},
};

static token_type q_tokens[] =
{
   {0},
};

static token_type r_tokens[] =
{
   {"rcl",           tSHIFT,        2},
   {"rcpps"},
   {"rcpss"},
   {"rcr",           tSHIFT,        3},
   {"rdshr",         tTWOBYTE,      0x0F36},
   {"rdmsr",         tTWOBYTE,      0x0F32},
   {"rdpmc",         tTWOBYTE,      0x0F33},
   {"rdtsc",         tTWOBYTE,      0x0F31},
   {"rep"},
   {"repe"},
   {"repne"},
   {"repnz"},
   {"repz"},
   {"resb"},
   {"resd"},
   {"resq"},
   {"rest"},
   {"resw"},
   {"ret"},
   {"retf"},
   {"retn"},
   {"rol",           tSHIFT,        0},
   {"ror",           tSHIFT,        1},
   {"rsdc"},
   {"rsldt"},
   {"rsm",           tTWOBYTE,      0x0FAA},
   {"rsqrtps"},
   {"rsqrtss"},
   {0},
};

static token_type s_tokens[] =
{
   {"sahf",          tONEBYTE,      0x9E},
   {"sal",           tSHIFT,        4},
   {"salc"},
   {"sar",           tSHIFT,        6},
   {"sbb",           tARITH,        0x18},
   {"scas"},
   {"scasb",         tONEBYTE,      0xAE},
   {"scasd",         tONEBYTE32S,   0xAF},
   {"scasw",         tONEBYTE16S,   0xAF},
   {"seta",          tSETcc,        7},
   {"setae",         tSETcc,        3},
   {"setb",          tSETcc,        2},
   {"setbe",         tSETcc,        6},
   {"setc",          tSETcc,        2},
   {"sete",          tSETcc,        4},
   {"setg",          tSETcc,        15},
   {"setge",         tSETcc,        13},
   {"setl",          tSETcc,        12},
   {"setle",         tSETcc,        14},
   {"setna",         tSETcc,        6},
   {"setnae",        tSETcc,        2},
   {"setnb",         tSETcc,        3},
   {"setnbe",        tSETcc,        7},
   {"setnc",         tSETcc,        3},
   {"setne",         tSETcc,        5},
   {"setng",         tSETcc,        14},
   {"setnge",        tSETcc,        12},
   {"setnl",         tSETcc,        13},
   {"setnle",        tSETcc,        15},
   {"setno",         tSETcc,        1},
   {"setnp",         tSETcc,        11},
   {"setns",         tSETcc,        9},
   {"setnz",         tSETcc,        5},
   {"seto",          tSETcc,        0},
   {"setp",          tSETcc,        10},
   {"setpe",         tSETcc,        10},
   {"setpo",         tSETcc,        11},
   {"sets",          tSETcc,        8},
   {"setz",          tSETcc,        4},
   {"sfence",        tTHREEBYTE,    0x0FAEF8},
   {"sgdt"},
   {"shl",           tSHIFT,        4},
   {"shld"},
   {"shr",           tSHIFT,        5},
   {"shrd"},
   {"shufpd"},
   {"shufps"},
   {"shufss"},
   {"si",            tREG16,        6},
   {"sidt"},
   {"sldt"},
   {"smi",           tONEBYTE,      0xF1},
   {"smint",         tTWOBYTE,      0x0F38},
   {"smintold",      tTWOBYTE,      0x0F7E},
   {"smsw"},
   {"sp",            tREG16,        5},
   {"sqrtpd"},
   {"sqrtps"},
   {"sqrtsd"},
   {"sqrtss"},
   {"ss",            tSREG},
   {"stc",           tONEBYTE,      0xF9},
   {"std",           tONEBYTE,      0xFD},
   {"sti",           tONEBYTE,      0xFB},
   {"stmxcsr"},
   {"stos"},
   {"stosb",         tONEBYTE,      0xAA},
   {"stosd",         tONEBYTE32,    0xAB},
   {"stosw",         tONEBYTE16,    0xAB},
   {"str"},
   {"sub",           tARITH,        0x28},
   {"subpd"},
   {"subps"},
   {"subsd"},
   {"subss"},
   {"svdc"},
   {"svldt"},
   {"svts"},
   {"syscall",       tTWOBYTE,      0x0F05},
   {"sysenter",      tTWOBYTE,      0x0F34},
   {"sysexit",       tTWOBYTE,      0x0F36},
   {"sysret",        tTWOBYTE,      0x0F07},
   {0},
};

static token_type t_tokens[] =
{
   {"test",          tTEST,         0},
   {"tr0",           tTREG,         0},
   {"tr1",           tTREG,         1},
   {"tr2",           tTREG,         2},
   {"tr3",           tTREG,         3},
   {"tr4",           tTREG,         4},
   {"tr5",           tTREG,         5},
   {"tr6",           tTREG,         6},
   {"tr7",           tTREG,         7},
   {0},
};

static token_type u_tokens[] =
{
   {"ucomisd"},
   {"ucomiss"},
   {"ud1",           tTWOBYTE,      0x0FB9},
   {"ud2",           tTWOBYTE,      0x0F0B},
   {"umov"},
   {"unpckhpd"},
   {"unpckhps"},
   {"unpcklpd"},
   {"unpcklps"},
   {0},
};

static token_type v_tokens[] =
{
   {"verr"},
   {"verw"},
   {0},
};

static token_type w_tokens[] =
{
   {"wait",          tONEBYTE,      0x9B},
   {"wbinvd",        tTWOBYTE,      0x0F09},
   {"wrshr",         tTWOBYTE,      0x0F37},
   {"wrmsr",         tTWOBYTE,      0x0F30},
   {0},
};

static token_type x_tokens[] =
{
   {"xadd"},
   {"xbts"},
   {"xchg"},
   {"xlat"},
   {"xlatb",         tONEBYTE,      0xD7},
   {"xor",           tARITH,        0x30},
   {"xorpd"},
   {"xorps"},
   {0},
};

static token_type y_tokens[] =
{
   {0},
};

static token_type z_tokens[] =
{
   {0},
};

token_type *tokens[] =
{
   a_tokens, b_tokens, c_tokens, d_tokens, e_tokens,
   f_tokens, g_tokens, h_tokens, i_tokens, j_tokens,
   k_tokens, l_tokens, m_tokens, n_tokens, o_tokens,
   p_tokens, q_tokens, r_tokens, s_tokens, t_tokens,
   u_tokens, v_tokens, w_tokens, x_tokens, y_tokens,
   z_tokens,
};
